# Makefile for SSC compiler using Flex, Bison, and LLVM

# Compiler
CXX = clang++
LLVM_CONFIG = llvm-config
LLC = llc  # LLVM static compiler
OPT = opt  # LLVM optimizer

# Files
LEXER = ssc.l
PARSER = ssc.y
EXECUTABLE = ssc_compiler
TEST_FILE = input.ssc
IR_FILE = output.ll
OPT_IR_FILE = output_opt.ll  # Optimized LLVM IR
ASM_FILE = output.s
OBJ_FILE = output.o
BIN_FILE = ssc_compiler_ir

# Intermediate files generated by Flex and Bison
LEX_C = lex.yy.c
PARSER_C = ssc.tab.c
PARSER_H = ssc.tab.h

# LLVM configuration
LLVM_CXXFLAGS = $(shell $(LLVM_CONFIG) --cxxflags)
LLVM_LDFLAGS = $(shell $(LLVM_CONFIG) --ldflags)
LLVM_LIBS = $(shell $(LLVM_CONFIG) --libs)

# Bison and Flex flags
BISON_FLAGS = -d
FLEX_FLAGS =

# Optimization level for opt (e.g., -O2, -O3)
OPT_LEVEL = -O2

# Default target: compile the entire project
all: $(EXECUTABLE)

# Generate the parser using Bison
$(PARSER_C) $(PARSER_H): $(PARSER)
	bison $(BISON_FLAGS) -o $(PARSER_C) $(PARSER)

# Generate the lexer using Flex
$(LEX_C): $(LEXER)
	flex $(FLEX_FLAGS) -o $(LEX_C) $(LEXER)

# Compile the SSC compiler with LLVM support
$(EXECUTABLE): $(LEX_C) $(PARSER_C)
	$(CXX) $(LLVM_CXXFLAGS) -o $(EXECUTABLE) $(PARSER_C) $(LEX_C) $(LLVM_LDFLAGS) $(LLVM_LIBS)

# Generate intermediate LLVM IR
ir: $(IR_FILE)

$(IR_FILE): $(EXECUTABLE) $(TEST_FILE)
	./$(EXECUTABLE) $(TEST_FILE) > $(IR_FILE) 2>&1
	test -s $(IR_FILE) || (echo "Error: output.ll is empty" && exit 1)

# Optimize the LLVM IR using opt
opt: $(OPT_IR_FILE)

$(OPT_IR_FILE): $(IR_FILE)
	$(OPT) $(OPT_LEVEL) $(IR_FILE) -S -o $(OPT_IR_FILE)

# Compile LLVM IR to assembly
$(ASM_FILE): $(IR_FILE)
	$(LLC) -filetype=asm $(IR_FILE) -o $(ASM_FILE)

# Compile assembly to an object file
$(OBJ_FILE): $(ASM_FILE)
	clang -c $(ASM_FILE) -o $(OBJ_FILE)

# Link the object file to create an executable
$(BIN_FILE): $(OBJ_FILE)
	clang -o $(BIN_FILE) $(OBJ_FILE) -lc

# Run the SSC compiler to generate IR, compile it, and run the executable
run: ir
	llc -filetype=obj output.ll -o output.o
	clang output.o -o ssc_compiler_ir -no-pie -lc
	./ssc_compiler_ir

# Run the SSC compiler with optimized IR
run_opt: opt
	llc -filetype=obj $(OPT_IR_FILE) -o output.o
	clang output.o -o ssc_compiler_ir -no-pie -lc
	./ssc_compiler_ir

# Debug target: run the compiler without redirecting output
debug: $(EXECUTABLE)
	./$(EXECUTABLE) $(TEST_FILE)

# Clean up generated files
clean:
	rm -f $(LEX_C) $(PARSER_C) $(PARSER_H) $(EXECUTABLE) $(IR_FILE) $(OPT_IR_FILE) $(ASM_FILE) $(OBJ_FILE) $(BIN_FILE)

# Clean all generated files and any additional outputs
distclean: clean
	rm -f a.out ssc.output

# Show available Makefile commands
help:
	@echo "Available targets:"
	@echo "  make         - Compile the SSC compiler"
	@echo "  make ir      - Generate intermediate LLVM IR (output.ll)"
	@echo "  make opt     - Optimize the LLVM IR (output_opt.ll)"
	@echo "  make run     - Generate IR, compile it, and run the executable"
	@echo "  make run_opt - Generate optimized IR, compile it, and run the executable"
	@echo "  make debug   - Run the compiler without redirecting output (for debugging)"
	@echo "  make clean   - Remove compiled and intermediate files"
	@echo "  make distclean - Remove all build files and output"
	@echo "  make help    - Display this help message"

# Phony targets
.PHONY: all ir opt run run_opt debug clean distclean help
